### PR TITLE
Fix variables using roof-duality

### PR DESCRIPTION
**Pull request by hsadeghidw**
Fix variables using roof-duality.
It roughly fixes 2/3 of the variables...

### CODE REVIEW

**Review by randomir — COMMENTED** [review]
This is great. My only concern is it adds another new concept to a simple example (where the emphasis is on problem construction and calling a hybrid solver).

Maybe creating a new example which would focus on different (pre-)solving techniques would make more sense? (e.g. roof duality, disconnected components composite, spin reversal transform, greedy descent postprocess, etc)

If we decide to merge it here, we should at least document very clearly what `fix_variables()` does.

Thoughts, @arcondello?

**Comment by hsadeghidw** [comment]
Good point @randomir 
I think since this is not too complicated and it gives a good idea of how some of the Ocean tools can be used together, it's okay to add tricks like to this to many of the examples. but I totally see your point.

Anyways, I was just passing by, and it occurred to me that many variables are fixable...

I can close this if you like...

**Comment by arcondello** [comment]
What about using roof duality in `KerberosSampler`?

**Comment by hsadeghidw** [comment]
There is an up-side to having explicit fix_variables, it is more instructive, but from the software development point of view, obviously, that should go to the sampler.

**Comment by randomir** [comment]
I see your point, @hsadeghidw. This is not too complicated, but a lot of tricks/ideas like this can add up. I believe it's better for each demo/example to focus on just one area (that's bqm construction from a problem here). And then we can have examples that build on top of previous examples.

Since roof duality fixes majority of variables here, and we were forced to use KerberosSampler because the problem wouldn't fit on the QPU (IIRC), seems like Sudoku example would be a perfect candidate to build pre-processing techniques example on.

**Comment by randomir** [comment]
@arcondello, roof duality in `KerberosSampler` makes sense. We can do that.

FWIW, it would be also be valuable to teach users they can do:
```
workflow = hybrid.RoofDualityDecomposer() | hybrid.Kerberos()
```
or, as sampler:
```
sampler = hybrid.HybridSampler(hybrid.RoofDualityDecomposer() | hybrid.Kerberos())
```

**Comment by JoelPasvolsky** [comment]
My Hybrid Computing JN has a postprocessing section, it could happily get a preprocessing one

**Pull request closed without merging**
